# Generated by Django 5.0.6 on 2024-09-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="age",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="city_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="district_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_phone_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="postcode",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="social_media_links",
        ),
        migrations.AddField(
            model_name="customuser",
            name="facebook_profile",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="headline",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="linkedin_profile",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="twitter_profile",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="youtube_profile",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
