# Generated by Django 5.0.6 on 2024-09-16 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0003_remove_enrollment_course_remove_enrollment_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("max_students", models.IntegerField(default=0)),
                ("difficulty_level", models.CharField(max_length=50)),
                ("is_public", models.BooleanField(default=False)),
                ("qa_enabled", models.BooleanField(default=False)),
                ("course_benefits", models.TextField(blank=True)),
                ("target_audience", models.TextField(blank=True)),
                ("course_duration_hours", models.IntegerField(default=0)),
                ("course_duration_minutes", models.IntegerField(default=0)),
                ("materials_included", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("video", models.FileField(blank=True, upload_to="course_videos/")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_enrolled", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
