# Generated by Django 5.0.6 on 2024-09-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_place', models.CharField(max_length=255)),
                ('destination_place', models.CharField(max_length=255)),
                ('waiting_place', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
                ('leaving_time', models.TimeField()),
                ('waiting_time', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
